// <auto-generated />
using System;
using BeeFriend.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeeFriend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CountryId = 1,
                            Latitude = 42.697699999999998,
                            Longitude = 23.321899999999999,
                            Name = "Sofia"
                        },
                        new
                        {
                            CityId = 2,
                            CountryId = 1,
                            Latitude = 42.135399999999997,
                            Longitude = 24.7453,
                            Name = "Plovdiv"
                        },
                        new
                        {
                            CityId = 3,
                            CountryId = 1,
                            Latitude = 43.214100000000002,
                            Longitude = 27.9147,
                            Name = "Varna"
                        },
                        new
                        {
                            CityId = 4,
                            CountryId = 1,
                            Latitude = 42.504800000000003,
                            Longitude = 27.462599999999998,
                            Name = "Burgas"
                        },
                        new
                        {
                            CityId = 5,
                            CountryId = 2,
                            Latitude = 52.520000000000003,
                            Longitude = 13.404999999999999,
                            Name = "Berlin"
                        },
                        new
                        {
                            CityId = 6,
                            CountryId = 2,
                            Latitude = 48.135100000000001,
                            Longitude = 11.582000000000001,
                            Name = "Munich"
                        },
                        new
                        {
                            CityId = 7,
                            CountryId = 2,
                            Latitude = 53.551099999999998,
                            Longitude = 9.9937000000000005,
                            Name = "Hamburg"
                        },
                        new
                        {
                            CityId = 8,
                            CountryId = 2,
                            Latitude = 50.110900000000001,
                            Longitude = 8.6821000000000002,
                            Name = "Frankfurt"
                        },
                        new
                        {
                            CityId = 9,
                            CountryId = 3,
                            Latitude = 48.8566,
                            Longitude = 2.3521999999999998,
                            Name = "Paris"
                        },
                        new
                        {
                            CityId = 10,
                            CountryId = 3,
                            Latitude = 43.296500000000002,
                            Longitude = 5.3697999999999997,
                            Name = "Marseille"
                        },
                        new
                        {
                            CityId = 11,
                            CountryId = 3,
                            Latitude = 45.764000000000003,
                            Longitude = 4.8357000000000001,
                            Name = "Lyon"
                        },
                        new
                        {
                            CityId = 12,
                            CountryId = 4,
                            Latitude = 41.902799999999999,
                            Longitude = 12.4964,
                            Name = "Rome"
                        },
                        new
                        {
                            CityId = 13,
                            CountryId = 4,
                            Latitude = 45.464199999999998,
                            Longitude = 9.1899999999999995,
                            Name = "Milan"
                        },
                        new
                        {
                            CityId = 14,
                            CountryId = 4,
                            Latitude = 40.851799999999997,
                            Longitude = 14.2681,
                            Name = "Naples"
                        },
                        new
                        {
                            CityId = 15,
                            CountryId = 5,
                            Latitude = 40.416800000000002,
                            Longitude = -3.7038000000000002,
                            Name = "Madrid"
                        },
                        new
                        {
                            CityId = 16,
                            CountryId = 5,
                            Latitude = 41.385100000000001,
                            Longitude = 2.1734,
                            Name = "Barcelona"
                        },
                        new
                        {
                            CityId = 17,
                            CountryId = 5,
                            Latitude = 39.469900000000003,
                            Longitude = -0.37630000000000002,
                            Name = "Valencia"
                        },
                        new
                        {
                            CityId = 18,
                            CountryId = 6,
                            Latitude = 51.507399999999997,
                            Longitude = -0.1278,
                            Name = "London"
                        },
                        new
                        {
                            CityId = 19,
                            CountryId = 6,
                            Latitude = 53.480800000000002,
                            Longitude = -2.2425999999999999,
                            Name = "Manchester"
                        },
                        new
                        {
                            CityId = 20,
                            CountryId = 6,
                            Latitude = 52.486199999999997,
                            Longitude = -1.8904000000000001,
                            Name = "Birmingham"
                        },
                        new
                        {
                            CityId = 21,
                            CountryId = 7,
                            Latitude = 44.4268,
                            Longitude = 26.102499999999999,
                            Name = "Bucharest"
                        },
                        new
                        {
                            CityId = 22,
                            CountryId = 7,
                            Latitude = 46.7712,
                            Longitude = 23.6236,
                            Name = "Cluj-Napoca"
                        },
                        new
                        {
                            CityId = 23,
                            CountryId = 8,
                            Latitude = 37.983800000000002,
                            Longitude = 23.727499999999999,
                            Name = "Athens"
                        },
                        new
                        {
                            CityId = 24,
                            CountryId = 8,
                            Latitude = 40.640099999999997,
                            Longitude = 22.944400000000002,
                            Name = "Thessaloniki"
                        },
                        new
                        {
                            CityId = 25,
                            CountryId = 9,
                            Latitude = 48.208199999999998,
                            Longitude = 16.373799999999999,
                            Name = "Vienna"
                        },
                        new
                        {
                            CityId = 26,
                            CountryId = 9,
                            Latitude = 47.8095,
                            Longitude = 13.055,
                            Name = "Salzburg"
                        },
                        new
                        {
                            CityId = 27,
                            CountryId = 10,
                            Latitude = 52.367600000000003,
                            Longitude = 4.9040999999999997,
                            Name = "Amsterdam"
                        },
                        new
                        {
                            CityId = 28,
                            CountryId = 10,
                            Latitude = 51.924399999999999,
                            Longitude = 4.4776999999999996,
                            Name = "Rotterdam"
                        },
                        new
                        {
                            CityId = 29,
                            CountryId = 11,
                            Latitude = 52.229700000000001,
                            Longitude = 21.0122,
                            Name = "Warsaw"
                        },
                        new
                        {
                            CityId = 30,
                            CountryId = 11,
                            Latitude = 50.064700000000002,
                            Longitude = 19.945,
                            Name = "Krakow"
                        },
                        new
                        {
                            CityId = 31,
                            CountryId = 12,
                            Latitude = 50.075499999999998,
                            Longitude = 14.437799999999999,
                            Name = "Prague"
                        },
                        new
                        {
                            CityId = 32,
                            CountryId = 12,
                            Latitude = 49.195099999999996,
                            Longitude = 16.6068,
                            Name = "Brno"
                        });
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Germany"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "France"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "Italy"
                        },
                        new
                        {
                            CountryId = 5,
                            Name = "Spain"
                        },
                        new
                        {
                            CountryId = 6,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            CountryId = 7,
                            Name = "Romania"
                        },
                        new
                        {
                            CountryId = 8,
                            Name = "Greece"
                        },
                        new
                        {
                            CountryId = 9,
                            Name = "Austria"
                        },
                        new
                        {
                            CountryId = 10,
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryId = 11,
                            Name = "Poland"
                        },
                        new
                        {
                            CountryId = 12,
                            Name = "Czech Republic"
                        });
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.FriendshipPreference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreferenceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PreferenceId");

                    b.ToTable("FriendshipPreferences");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("InterestId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.InterestCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryId");

                    b.ToTable("InterestCategories");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.Personality", b =>
                {
                    b.Property<int>("PerosnalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerosnalityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PerosnalityId");

                    b.ToTable("PersonalityTraits");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("Pronouns")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.IdentityEntities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.IdentityEntities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FriendshipPreferenceUserProfile", b =>
                {
                    b.Property<int>("FriendshipPreferencesPreferenceId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsersUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FriendshipPreferencesPreferenceId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("FriendshipPreferenceUserProfile");
                });

            modelBuilder.Entity("InterestUserProfile", b =>
                {
                    b.Property<int>("InterestsInterestId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsersUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InterestsInterestId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("InterestUserProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PersonalityUserProfile", b =>
                {
                    b.Property<int>("PersonalityTraitsPerosnalityId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsersUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonalityTraitsPerosnalityId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("PersonalityUserProfile");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.City", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.Interest", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.Entities.InterestCategory", "Category")
                        .WithMany("Interests")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.Entities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId");

                    b.HasOne("BeeFriend.Core.Domain.Entities.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId");

                    b.HasOne("BeeFriend.Core.Domain.IdentityEntities.ApplicationUser", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("BeeFriend.Core.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FriendshipPreferenceUserProfile", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.Entities.FriendshipPreference", null)
                        .WithMany()
                        .HasForeignKey("FriendshipPreferencesPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeeFriend.Core.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterestUserProfile", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.Entities.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeeFriend.Core.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeeFriend.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalityUserProfile", b =>
                {
                    b.HasOne("BeeFriend.Core.Domain.Entities.Personality", null)
                        .WithMany()
                        .HasForeignKey("PersonalityTraitsPerosnalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeeFriend.Core.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.City", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.Entities.InterestCategory", b =>
                {
                    b.Navigation("Interests");
                });

            modelBuilder.Entity("BeeFriend.Core.Domain.IdentityEntities.ApplicationUser", b =>
                {
                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
